{% set version = "1.3.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cvms
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cvms_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cvms/cvms_{{ version }}.tar.gz
  sha256: 9a2a5ba293a0a091c9aafd4e16169966eab513a1ad8cbec4f3310fec90eebd40

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate >=2.0.0
    - r-data.table >=1.12
    - r-dplyr >=0.8.5
    - r-ggplot2
    - r-groupdata2 >=2.0.1
    - r-lifecycle
    - r-lme4 >=1.1_23
    - r-mumin >=1.43.17
    - r-parameters >=0.15.0
    - r-plyr
    - r-proc >=1.16.0
    - r-purrr
    - r-rearrr >=0.3.0
    - r-recipes >=0.1.13
    - r-rlang >=0.4.7
    - r-stringr
    - r-tibble >=3.0.3
    - r-tidyr >=1.1.2
  run:
    - r-base
    - r-checkmate >=2.0.0
    - r-data.table >=1.12
    - r-dplyr >=0.8.5
    - r-ggplot2
    - r-groupdata2 >=2.0.1
    - r-lifecycle
    - r-lme4 >=1.1_23
    - r-mumin >=1.43.17
    - r-parameters >=0.15.0
    - r-plyr
    - r-proc >=1.16.0
    - r-purrr
    - r-rearrr >=0.3.0
    - r-recipes >=0.1.13
    - r-rlang >=0.4.7
    - r-stringr
    - r-tibble >=3.0.3
    - r-tidyr >=1.1.2

test:
  commands:
    - $R -e "library('cvms')"           # [not win]
    - "\"%R%\" -e \"library('cvms')\""  # [win]

about:
  home: https://github.com/ludvigolsen/cvms
  license: MIT
  summary: 'Cross-validate one or multiple regression and classification models and get relevant evaluation metrics in a tidy format. Validate the best model on a test set and compare it to a baseline evaluation. Alternatively, evaluate predictions from an external model. Currently supports regression and classification
    (binary and multiclass). Described in chp. 5 of Jeyaraman, B. P., Olsen, L. R., & Wambugu M. (2019, ISBN: 9781838550134).'
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
